#!/usr/bin/env node
const {execSync} = require('child_process')

try {
    execSync('npm run precommit');
} catch(e) {
    console.error(e.message);
    console.error(e.stderr.toString());
    console.error(e.stdout.toString());
    process.exit(1);
}